dependencies {
    implementation project(':model')
    implementation project(':log-util')
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.security:spring-security-core'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'
    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'
}