server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/auth_db
    username: root
    password: admin
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
    sql:
      init:
        mode: always
  application:
    name: "powerup-crediya-authentication"
  devtools:
    add-properties: false
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

# API Paths Configuration
api:
  paths:
    usuarios:
      base: "/api/v1/usuarios"
      validar-existencia-usuario: "/api/v1/usuarios/validar-existencia"
    roles: "/api/v1/roles"

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  info:
    title: "Crediya Authenticacion API"
    description: "API para la gestion de usuarios y roles de crediya"
    version: "1.0.0"
    contact:
      name: "Pragma Team"
      email: "support@pragma.com"
    license:
      name: "MIT"
      url: "https://opensource.org/licenses/MIT"
