name=PropertiesConfig
property.filename=logs
appenders=console
appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
# Logger específico para nuestro paquete
logger.pragma.name=co.com.pragma
logger.pragma.level=debug
logger.pragma.additivity=false
logger.pragma.appenderRefs=stdout
logger.pragma.appenderRef.stdout.ref=STDOUT
# Root logger con nivel INFO
rootLogger.level=info
rootLogger.appenderRefs=stdout
rootLogger.appenderRef.stdout.ref=STDOUT
